server:
  port: 5050
  servlet:
    application-display-name: boot-es

spring:
  profiles:
    active: dev
    application:
      name: ${server.servlet.application-display-name}
#  data:
#    elasticsearch:
#      cluster-name: testescluster
#      cluster-nodes: 172.17.11.96:9300
#      local: false
#      repositories:
#        enabled: true

elasticsearch:
  host: 172.17.5.218
  port: 9300
  clustername: testescluster

logging:
  level:
    root: INFO
  file: /apache-tomcat/logs/boot-es.log
  pattern:
    file: '%d [%thread] [%X{trace_id:--}] %-5level %logger - %msg%n'
    console: '%d [%thread] [%X{trace_id:--}] %-5level %logger - %msg%n'